general:
  csv_name: cifar10_resnet_instances.csv
  root_path: ../../vnncomp2021/benchmarks/cifar10_resnet
data:
  end: 72
  dataset: CIFAR
specification:
  norm: .inf
solver:
  batch_size: 2000
  auto_enlarge_batch_size: true
  beta-crown:
    lr_beta: 0.01
bab:
  interm_transfer: false
  tree_traversal: breadth_first
  cut:
    enabled: true
    bab_cut: true
    number_cuts: 500
    biccos:
      enabled: true
      auto_param: false
      multi_tree_branching:
        enabled: true
        restore_best_tree: true
  branching:
    reduceop: max
attack:
  pgd_order: middle
