general:
  csv_name: cifar10_resnet_instances.csv
  root_path: ../../vnncomp2021/benchmarks/cifar10_resnet
data:
  end: 72
  dataset: CIFAR
specification:
  norm: .inf
solver:
  batch_size: 2000
  auto_enlarge_batch_size: true
  beta-crown:
    lr_beta: 0.01
bab:
  interm_transfer: false
  cut:
    enabled: true
    bab_cut: true
    number_cuts: 500
    cplex_cuts: true
  branching:
    reduceop: max
attack:
  pgd_order: middle
