general:
  root_path: ../../vnncomp2024_benchmarks/benchmarks/cifar100
  csv_name: instances.csv
model:
  onnx_optimization_flags: ["merge_bn"]
attack:
  pgd_order: middle
  pgd_restarts: 10
solver:
  auto_enlarge_batch_size: True
  batch_size: 256
  beta-crown:
    lr_alpha: 0.1
    lr_beta: 0.2
    iteration: 10
  alpha-crown:
    lr_alpha: 0.25
    iteration: 20
    full_conv_alpha: False
  prune_after_crown: True
bab:
  initial_max_domains: 100
  interm_transfer: False
  branching:
    method: kfsb
    candidates: 7
    reduceop: max