general:
  root_path: ../../vnncomp2024_benchmarks/benchmarks/neuralsat_generation_benchmark
  csv_name: instances.csv
  complete_verifier: auto
model:
  onnx_optimization_flags: ["merge_bn"]
  onnx_quirks: "{'Reshape': {'fix_batch_size': True}}"
attack:
  pgd_order: middle
  pgd_restarts: 10
solver:
  auto_enlarge_batch_size: True
  prune_after_crown: True
  batch_size: 256
  beta-crown:
    lr_alpha: 0.05
    lr_beta: 0.2
    iteration: 20
  alpha-crown:
    lr_alpha: 0.25
    iteration: 20
    full_conv_alpha: False
  mip:
    parallel_solvers: 32
    solver_threads: 1
    refine_neuron_time_percentage: 0.8
    refine_neuron_timeout: 15
    remove_unstable_neurons: True
    sliding_window: 5
bab:
  initial_max_domains: 100
  interm_transfer: False
  branching:
    candidates: 3
    reduceop: max