model:
  name: cnn_4layer_adv
  path: models/sdp/cifar_cnn_a_adv.model
data:
  dataset: CIFAR_SDP
specification:
  norm: .inf
  epsilon: 0.00784313725
solver:
  batch_size: 4096
  auto_enlarge_batch_size: true
  beta-crown:
    iteration: 20
bab:
  timeout: 200
  interm_transfer: false
  cut:
    enabled: true
    bab_cut: true
    number_cuts: 500
    cplex_cuts: true
  branching:
    reduceop: max
attack:
  pgd_order: middle
  pgd_restarts: 50
