# Configuration file for running the ACASXu benchmark (all properties).
general:
  root_path: ../../vnncomp2023_benchmarks/benchmarks/acasxu  # Please clone the vnncomp2023 repo first as it contains the benchmark.
  csv_name: instances.csv
  enable_incomplete_verification: False
solver:
  batch_size: 16384  # Number of parallel domains to compute on GPU.
  bound_prop_method: crown
bab:
  branching:
    method: naive  # Split on input space.
    input_split:
      enable: True
      enable_clip_domains: True
      reorder_bab: True
attack:
  pgd_order: after
  pgd_restarts: 10000
  pgd_restart_when_stuck: True
