general:
  root_path: ../../vnncomp2023_benchmarks/benchmarks/metaroom
  csv_name: instances.csv
model:
  onnx_quirks: "{'Reshape': {'fix_batch_size': True}}"
solver:
  batch_size: 384
  beta-crown:
    lr_alpha: 0.1
    lr_beta: 0.2
    iteration: 50
  alpha-crown:
    lr_alpha: 0.25
    iteration: 100
  prune_after_crown: True
bab:
  initial_max_domains: 100
  branching:
    reduceop: max
    candidates: 10
  interm_transfer: False
attack:
  pgd_order: middle
