# Configuration file for running the vggnet16_2022 benchmark (all properties).
general:
  root_path: ../../vnncomp2023_benchmarks/benchmarks/vggnet16
  csv_name: instances.csv
  enable_incomplete_verification: False
  loss_reduction_func: max
  graph_optimizer: Customized("custom_graph_optimizer", "maxpool_to_relu")
model:
  cache_onnx_conversion: True
solver:
  batch_size: 1  # Number of parallel domains to compute on GPU.
  bound_prop_method: dynamic-forward+backward
  forward:
    max_dim: 100
  beta-crown:
    iteration: 10  # Iterations for computing intermediate layer bounds.
  crown:
    batch_size: 64
bab:
  branching:
    method: sb
    input_split:
      enable: True
attack:
  pgd_order: input_bab
  check_clean: True
