general:
  csv_name: instances.csv
  root_path: ../../vnncomp2022_benchmarks/benchmarks/cifar100_tinyimagenet_resnet
model:
  onnx_optimization_flags: merge_bn
data:
  start: 34
  end: 58
  num_outputs: 100
specification:
  norm: .inf
solver:
  batch_size: 256
  alpha-crown:
    lr_alpha: 0.25
    iteration: 20
    full_conv_alpha: false
  beta-crown:
    lr_alpha: 0.05
    lr_beta: 0.1
    iteration: 5
bab:
  interm_transfer: false
  tree_traversal: breadth_first
  cut:
    enabled: true
    bab_cut: true
    number_cuts: 500
    biccos:
      enabled: true
      auto_param: false
      multi_tree_branching:
        enabled: true
        restore_best_tree: true
  branching:
    candidates: 7
    reduceop: max
attack:
  pgd_order: middle
  pgd_restarts: 10
